// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0scArDocWtpzpeT05eO0-MgEN8IEMHg',
    appId: '1:94336636089:web:6d6e950065bca05ebc7768',
    messagingSenderId: '94336636089',
    projectId: 'fir-e-task',
    authDomain: 'fir-e-task.firebaseapp.com',
    storageBucket: 'fir-e-task.firebasestorage.app',
    measurementId: 'G-299RF7DJZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5b2KJtHmkLI2FRo71NCeoWv9iaR9KwI',
    appId: '1:94336636089:android:157e3497136a7cbfbc7768',
    messagingSenderId: '94336636089',
    projectId: 'fir-e-task',
    storageBucket: 'fir-e-task.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yA9piHAd8yjwjK3Ty-DmCEu7rzSW5JA',
    appId: '1:94336636089:ios:2c4ad8704133af22bc7768',
    messagingSenderId: '94336636089',
    projectId: 'fir-e-task',
    storageBucket: 'fir-e-task.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6yA9piHAd8yjwjK3Ty-DmCEu7rzSW5JA',
    appId: '1:94336636089:ios:2c4ad8704133af22bc7768',
    messagingSenderId: '94336636089',
    projectId: 'fir-e-task',
    storageBucket: 'fir-e-task.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY0scArDocWtpzpeT05eO0-MgEN8IEMHg',
    appId: '1:94336636089:web:becfed8efcfddb00bc7768',
    messagingSenderId: '94336636089',
    projectId: 'fir-e-task',
    authDomain: 'fir-e-task.firebaseapp.com',
    storageBucket: 'fir-e-task.firebasestorage.app',
    measurementId: 'G-F86TSLJRTE',
  );
}
